/*
 * Openfort API
 *
 * Complete Openfort API references and guides can be found at: https://openfort.xyz/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;


namespace Openfort.OpenfortSDK.Model
{
    /// <summary>
    /// Defines APITopic
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum APITopic
    {
        /// <summary>
        /// Enum TransactionIntentBroadcast for value: transaction_intent.broadcast
        /// </summary>
        [EnumMember(Value = "transaction_intent.broadcast")]
        TransactionIntentBroadcast = 1,

        /// <summary>
        /// Enum TransactionIntentSuccessful for value: transaction_intent.successful
        /// </summary>
        [EnumMember(Value = "transaction_intent.successful")]
        TransactionIntentSuccessful = 2,

        /// <summary>
        /// Enum TransactionIntentCancelled for value: transaction_intent.cancelled
        /// </summary>
        [EnumMember(Value = "transaction_intent.cancelled")]
        TransactionIntentCancelled = 3,

        /// <summary>
        /// Enum TransactionIntentFailed for value: transaction_intent.failed
        /// </summary>
        [EnumMember(Value = "transaction_intent.failed")]
        TransactionIntentFailed = 4,

        /// <summary>
        /// Enum BalanceProject for value: balance.project
        /// </summary>
        [EnumMember(Value = "balance.project")]
        BalanceProject = 5,

        /// <summary>
        /// Enum BalanceContract for value: balance.contract
        /// </summary>
        [EnumMember(Value = "balance.contract")]
        BalanceContract = 6,

        /// <summary>
        /// Enum BalanceDevAccount for value: balance.dev_account
        /// </summary>
        [EnumMember(Value = "balance.dev_account")]
        BalanceDevAccount = 7,

        /// <summary>
        /// Enum Test for value: test
        /// </summary>
        [EnumMember(Value = "test")]
        Test = 8

    }

}
