/*
 * Openfort API
 *
 * Complete Openfort API references and guides can be found at: https://openfort.xyz/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;

namespace Openfort.OpenfortSDK.Model
{
    /// <summary>
    /// AuthenticatedPlayerResponse
    /// </summary>
    [DataContract(Name = "AuthenticatedPlayerResponse")]
    public partial class AuthenticatedPlayerResponse : IEquatable<AuthenticatedPlayerResponse>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AuthenticatedPlayerResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AuthenticatedPlayerResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AuthenticatedPlayerResponse" /> class.
        /// </summary>
        /// <param name="player">player (required).</param>
        public AuthenticatedPlayerResponse(AuthPlayerResponse player = default(AuthPlayerResponse))
        {
            // to ensure "player" is required (not null)
            if (player == null)
            {
                throw new ArgumentNullException("player is a required property for AuthenticatedPlayerResponse and cannot be null");
            }
            this.Player = player;
        }

        /// <summary>
        /// Gets or Sets Player
        /// </summary>
        [DataMember(Name = "player", IsRequired = true, EmitDefaultValue = true)]
        public AuthPlayerResponse Player { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AuthenticatedPlayerResponse {\n");
            sb.Append("  Player: ").Append(Player).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AuthenticatedPlayerResponse);
        }

        /// <summary>
        /// Returns true if AuthenticatedPlayerResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of AuthenticatedPlayerResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AuthenticatedPlayerResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return
                (
                    this.Player == input.Player ||
                    (this.Player != null &&
                    this.Player.Equals(input.Player))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Player != null)
                {
                    hashCode = (hashCode * 59) + this.Player.GetHashCode();
                }
                return hashCode;
            }
        }

    }

}
