/*
 * Openfort API
 *
 * Complete Openfort API references and guides can be found at: https://openfort.xyz/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;

namespace Openfort.OpenfortSDK.Model
{
    /// <summary>
    /// AuthorizePlayerRequest
    /// </summary>
    [DataContract(Name = "AuthorizePlayerRequest")]
    public partial class AuthorizePlayerRequest : IEquatable<AuthorizePlayerRequest>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AuthorizePlayerRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AuthorizePlayerRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AuthorizePlayerRequest" /> class.
        /// </summary>
        /// <param name="authorizationCode">The authorization code received from the api to authorize the project to use the Ecosystem player. (required).</param>
        public AuthorizePlayerRequest(string authorizationCode = default(string))
        {
            // to ensure "authorizationCode" is required (not null)
            if (authorizationCode == null)
            {
                throw new ArgumentNullException("authorizationCode is a required property for AuthorizePlayerRequest and cannot be null");
            }
            this.AuthorizationCode = authorizationCode;
        }

        /// <summary>
        /// The authorization code received from the api to authorize the project to use the Ecosystem player.
        /// </summary>
        /// <value>The authorization code received from the api to authorize the project to use the Ecosystem player.</value>
        /// <example>&quot;d9e215f74e715853&quot;</example>
        [DataMember(Name = "authorizationCode", IsRequired = true, EmitDefaultValue = true)]
        public string AuthorizationCode { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AuthorizePlayerRequest {\n");
            sb.Append("  AuthorizationCode: ").Append(AuthorizationCode).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AuthorizePlayerRequest);
        }

        /// <summary>
        /// Returns true if AuthorizePlayerRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of AuthorizePlayerRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AuthorizePlayerRequest input)
        {
            if (input == null)
            {
                return false;
            }
            return
                (
                    this.AuthorizationCode == input.AuthorizationCode ||
                    (this.AuthorizationCode != null &&
                    this.AuthorizationCode.Equals(input.AuthorizationCode))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.AuthorizationCode != null)
                {
                    hashCode = (hashCode * 59) + this.AuthorizationCode.GetHashCode();
                }
                return hashCode;
            }
        }

    }

}
