/*
 * Openfort API
 *
 * Complete Openfort API references and guides can be found at: https://openfort.xyz/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;


namespace Openfort.OpenfortSDK.Model
{
    /// <summary>
    /// CreateDeviceRequest
    /// </summary>
    [DataContract(Name = "CreateDeviceRequest")]
    public partial class CreateDeviceRequest : IEquatable<CreateDeviceRequest>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateDeviceRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreateDeviceRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateDeviceRequest" /> class.
        /// </summary>
        /// <param name="account">Specifies the unique account ID (starts with acc_) (required).</param>
        /// <param name="share">Specifies the share data (required).</param>
        public CreateDeviceRequest(string account = default(string), string share = default(string))
        {
            // to ensure "account" is required (not null)
            if (account == null)
            {
                throw new ArgumentNullException("account is a required property for CreateDeviceRequest and cannot be null");
            }
            this.Account = account;
            // to ensure "share" is required (not null)
            if (share == null)
            {
                throw new ArgumentNullException("share is a required property for CreateDeviceRequest and cannot be null");
            }
            this.Share = share;
        }

        /// <summary>
        /// Specifies the unique account ID (starts with acc_)
        /// </summary>
        /// <value>Specifies the unique account ID (starts with acc_)</value>
        /// <example>&quot;acc_6f6c9067-89fa-4fc8-ac72-c242a268c584&quot;</example>
        [DataMember(Name = "account", IsRequired = true, EmitDefaultValue = true)]
        public string Account { get; set; }

        /// <summary>
        /// Specifies the share data
        /// </summary>
        /// <value>Specifies the share data</value>
        /// <example>&quot;7d526b7e99fbf52850a183...&quot;</example>
        [DataMember(Name = "share", IsRequired = true, EmitDefaultValue = true)]
        public string Share { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateDeviceRequest {\n");
            sb.Append("  Account: ").Append(Account).Append("\n");
            sb.Append("  Share: ").Append(Share).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CreateDeviceRequest);
        }

        /// <summary>
        /// Returns true if CreateDeviceRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of CreateDeviceRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreateDeviceRequest input)
        {
            if (input == null)
            {
                return false;
            }
            return
                (
                    this.Account == input.Account ||
                    (this.Account != null &&
                    this.Account.Equals(input.Account))
                ) &&
                (
                    this.Share == input.Share ||
                    (this.Share != null &&
                    this.Share.Equals(input.Share))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Account != null)
                {
                    hashCode = (hashCode * 59) + this.Account.GetHashCode();
                }
                if (this.Share != null)
                {
                    hashCode = (hashCode * 59) + this.Share.GetHashCode();
                }
                return hashCode;
            }
        }

    }

}
