/*
 * Openfort API
 *
 * Complete Openfort API references and guides can be found at: https://openfort.xyz/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;

namespace Openfort.OpenfortSDK.Model
{
    /// <summary>
    /// CreateForwarderContractRequest
    /// </summary>
    [DataContract(Name = "CreateForwarderContractRequest")]
    public partial class CreateForwarderContractRequest : IEquatable<CreateForwarderContractRequest>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateForwarderContractRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreateForwarderContractRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateForwarderContractRequest" /> class.
        /// </summary>
        /// <param name="address">Specifies the address of the paymaster (required).</param>
        /// <param name="chainId">The chain ID. Must be a [supported chain](/chains). (required).</param>
        /// <param name="name">Specifies the name of the paymaster.</param>
        public CreateForwarderContractRequest(string address = default(string), int chainId = default(int), string name = default(string))
        {
            // to ensure "address" is required (not null)
            if (address == null)
            {
                throw new ArgumentNullException("address is a required property for CreateForwarderContractRequest and cannot be null");
            }
            this.Address = address;
            this.ChainId = chainId;
            this.Name = name;
        }

        /// <summary>
        /// Specifies the address of the paymaster
        /// </summary>
        /// <value>Specifies the address of the paymaster</value>
        /// <example>&quot;0x7d526b7e99fbf52850a183...&quot;</example>
        [DataMember(Name = "address", IsRequired = true, EmitDefaultValue = true)]
        public string Address { get; set; }

        /// <summary>
        /// The chain ID. Must be a [supported chain](/chains).
        /// </summary>
        /// <value>The chain ID. Must be a [supported chain](/chains).</value>
        /// <example>80002</example>
        [DataMember(Name = "chainId", IsRequired = true, EmitDefaultValue = true)]
        public int ChainId { get; set; }

        /// <summary>
        /// Specifies the name of the paymaster
        /// </summary>
        /// <value>Specifies the name of the paymaster</value>
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateForwarderContractRequest {\n");
            sb.Append("  Address: ").Append(Address).Append("\n");
            sb.Append("  ChainId: ").Append(ChainId).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CreateForwarderContractRequest);
        }

        /// <summary>
        /// Returns true if CreateForwarderContractRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of CreateForwarderContractRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreateForwarderContractRequest input)
        {
            if (input == null)
            {
                return false;
            }
            return
                (
                    this.Address == input.Address ||
                    (this.Address != null &&
                    this.Address.Equals(input.Address))
                ) &&
                (
                    this.ChainId == input.ChainId ||
                    this.ChainId.Equals(input.ChainId)
                ) &&
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Address != null)
                {
                    hashCode = (hashCode * 59) + this.Address.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.ChainId.GetHashCode();
                if (this.Name != null)
                {
                    hashCode = (hashCode * 59) + this.Name.GetHashCode();
                }
                return hashCode;
            }
        }

    }

}
