/*
 * Openfort API
 *
 * Complete Openfort API references and guides can be found at: https://openfort.xyz/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;


namespace Openfort.OpenfortSDK.Model
{
    /// <summary>
    /// CreateSMTPConfigRequest
    /// </summary>
    [DataContract(Name = "CreateSMTPConfigRequest")]
    public partial class CreateSMTPConfigRequest : IEquatable<CreateSMTPConfigRequest>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateSMTPConfigRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreateSMTPConfigRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateSMTPConfigRequest" /> class.
        /// </summary>
        /// <param name="user">Specifies the user name (required).</param>
        /// <param name="pass">Specifies the password (required).</param>
        /// <param name="host">Specifies the host (required).</param>
        /// <param name="from">Specifies the from (required).</param>
        /// <param name="port">Specifies the port (required).</param>
        /// <param name="useSSL">Specifies the use SSL (required).</param>
        public CreateSMTPConfigRequest(string user = default(string), string pass = default(string), string host = default(string), string from = default(string), double port = default(double), bool useSSL = default(bool))
        {
            // to ensure "user" is required (not null)
            if (user == null)
            {
                throw new ArgumentNullException("user is a required property for CreateSMTPConfigRequest and cannot be null");
            }
            this.User = user;
            // to ensure "pass" is required (not null)
            if (pass == null)
            {
                throw new ArgumentNullException("pass is a required property for CreateSMTPConfigRequest and cannot be null");
            }
            this.Pass = pass;
            // to ensure "host" is required (not null)
            if (host == null)
            {
                throw new ArgumentNullException("host is a required property for CreateSMTPConfigRequest and cannot be null");
            }
            this.Host = host;
            // to ensure "from" is required (not null)
            if (from == null)
            {
                throw new ArgumentNullException("from is a required property for CreateSMTPConfigRequest and cannot be null");
            }
            this.From = from;
            this.Port = port;
            this.UseSSL = useSSL;
        }

        /// <summary>
        /// Specifies the user name
        /// </summary>
        /// <value>Specifies the user name</value>
        /// <example>&quot;user&quot;</example>
        [DataMember(Name = "user", IsRequired = true, EmitDefaultValue = true)]
        public string User { get; set; }

        /// <summary>
        /// Specifies the password
        /// </summary>
        /// <value>Specifies the password</value>
        /// <example>&quot;pass&quot;</example>
        [DataMember(Name = "pass", IsRequired = true, EmitDefaultValue = true)]
        public string Pass { get; set; }

        /// <summary>
        /// Specifies the host
        /// </summary>
        /// <value>Specifies the host</value>
        /// <example>&quot;host&quot;</example>
        [DataMember(Name = "host", IsRequired = true, EmitDefaultValue = true)]
        public string Host { get; set; }

        /// <summary>
        /// Specifies the from
        /// </summary>
        /// <value>Specifies the from</value>
        /// <example>&quot;from&quot;</example>
        [DataMember(Name = "from", IsRequired = true, EmitDefaultValue = true)]
        public string From { get; set; }

        /// <summary>
        /// Specifies the port
        /// </summary>
        /// <value>Specifies the port</value>
        /// <example>0</example>
        [DataMember(Name = "port", IsRequired = true, EmitDefaultValue = true)]
        public double Port { get; set; }

        /// <summary>
        /// Specifies the use SSL
        /// </summary>
        /// <value>Specifies the use SSL</value>
        /// <example>true</example>
        [DataMember(Name = "useSSL", IsRequired = true, EmitDefaultValue = true)]
        public bool UseSSL { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateSMTPConfigRequest {\n");
            sb.Append("  User: ").Append(User).Append("\n");
            sb.Append("  Pass: ").Append(Pass).Append("\n");
            sb.Append("  Host: ").Append(Host).Append("\n");
            sb.Append("  From: ").Append(From).Append("\n");
            sb.Append("  Port: ").Append(Port).Append("\n");
            sb.Append("  UseSSL: ").Append(UseSSL).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CreateSMTPConfigRequest);
        }

        /// <summary>
        /// Returns true if CreateSMTPConfigRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of CreateSMTPConfigRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreateSMTPConfigRequest input)
        {
            if (input == null)
            {
                return false;
            }
            return
                (
                    this.User == input.User ||
                    (this.User != null &&
                    this.User.Equals(input.User))
                ) &&
                (
                    this.Pass == input.Pass ||
                    (this.Pass != null &&
                    this.Pass.Equals(input.Pass))
                ) &&
                (
                    this.Host == input.Host ||
                    (this.Host != null &&
                    this.Host.Equals(input.Host))
                ) &&
                (
                    this.From == input.From ||
                    (this.From != null &&
                    this.From.Equals(input.From))
                ) &&
                (
                    this.Port == input.Port ||
                    this.Port.Equals(input.Port)
                ) &&
                (
                    this.UseSSL == input.UseSSL ||
                    this.UseSSL.Equals(input.UseSSL)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.User != null)
                {
                    hashCode = (hashCode * 59) + this.User.GetHashCode();
                }
                if (this.Pass != null)
                {
                    hashCode = (hashCode * 59) + this.Pass.GetHashCode();
                }
                if (this.Host != null)
                {
                    hashCode = (hashCode * 59) + this.Host.GetHashCode();
                }
                if (this.From != null)
                {
                    hashCode = (hashCode * 59) + this.From.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.Port.GetHashCode();
                hashCode = (hashCode * 59) + this.UseSSL.GetHashCode();
                return hashCode;
            }
        }

    }

}
