/*
 * Openfort API
 *
 * Complete Openfort API references and guides can be found at: https://openfort.xyz/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;

namespace Openfort.OpenfortSDK.Model
{
    /// <summary>
    /// DeleteSMTPConfigResponse
    /// </summary>
    [DataContract(Name = "DeleteSMTPConfigResponse")]
    public partial class DeleteSMTPConfigResponse : IEquatable<DeleteSMTPConfigResponse>
    {

        /// <summary>
        /// Gets or Sets Object
        /// </summary>
        [DataMember(Name = "object", IsRequired = true, EmitDefaultValue = true)]
        public EntityTypeSMTPCONFIG Object { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="DeleteSMTPConfigResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected DeleteSMTPConfigResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="DeleteSMTPConfigResponse" /> class.
        /// </summary>
        /// <param name="deleted">deleted (required).</param>
        /// <param name="_object">_object (required).</param>
        public DeleteSMTPConfigResponse(bool deleted = default(bool), EntityTypeSMTPCONFIG _object = default(EntityTypeSMTPCONFIG))
        {
            this.Deleted = deleted;
            this.Object = _object;
        }

        /// <summary>
        /// Gets or Sets Deleted
        /// </summary>
        [DataMember(Name = "deleted", IsRequired = true, EmitDefaultValue = true)]
        public bool Deleted { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DeleteSMTPConfigResponse {\n");
            sb.Append("  Deleted: ").Append(Deleted).Append("\n");
            sb.Append("  Object: ").Append(Object).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DeleteSMTPConfigResponse);
        }

        /// <summary>
        /// Returns true if DeleteSMTPConfigResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of DeleteSMTPConfigResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DeleteSMTPConfigResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return
                (
                    this.Deleted == input.Deleted ||
                    this.Deleted.Equals(input.Deleted)
                ) &&
                (
                    this.Object == input.Object ||
                    this.Object.Equals(input.Object)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.Deleted.GetHashCode();
                hashCode = (hashCode * 59) + this.Object.GetHashCode();
                return hashCode;
            }
        }

    }

}
