/*
 * Openfort API
 *
 * Complete Openfort API references and guides can be found at: https://openfort.xyz/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;

namespace Openfort.OpenfortSDK.Model
{
    /// <summary>
    /// LoginOIDCRequest
    /// </summary>
    [DataContract(Name = "LoginOIDCRequest")]
    public partial class LoginOIDCRequest : IEquatable<LoginOIDCRequest>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LoginOIDCRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected LoginOIDCRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="LoginOIDCRequest" /> class.
        /// </summary>
        /// <param name="identityToken">The identity token of the user. (required).</param>
        public LoginOIDCRequest(string identityToken = default(string))
        {
            // to ensure "identityToken" is required (not null)
            if (identityToken == null)
            {
                throw new ArgumentNullException("identityToken is a required property for LoginOIDCRequest and cannot be null");
            }
            this.IdentityToken = identityToken;
        }

        /// <summary>
        /// The identity token of the user.
        /// </summary>
        /// <value>The identity token of the user.</value>
        /// <example>&quot;token&quot;</example>
        [DataMember(Name = "identityToken", IsRequired = true, EmitDefaultValue = true)]
        public string IdentityToken { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class LoginOIDCRequest {\n");
            sb.Append("  IdentityToken: ").Append(IdentityToken).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as LoginOIDCRequest);
        }

        /// <summary>
        /// Returns true if LoginOIDCRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of LoginOIDCRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(LoginOIDCRequest input)
        {
            if (input == null)
            {
                return false;
            }
            return
                (
                    this.IdentityToken == input.IdentityToken ||
                    (this.IdentityToken != null &&
                    this.IdentityToken.Equals(input.IdentityToken))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.IdentityToken != null)
                {
                    hashCode = (hashCode * 59) + this.IdentityToken.GetHashCode();
                }
                return hashCode;
            }
        }

    }

}
