/*
 * Openfort API
 *
 * Complete Openfort API references and guides can be found at: https://openfort.xyz/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;


namespace Openfort.OpenfortSDK.Model
{
    /// <summary>
    /// Enum of the supporting OAuth providers.
    /// </summary>
    /// <value>Enum of the supporting OAuth providers.</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum OAuthProvider
    {
        /// <summary>
        /// Enum Google for value: google
        /// </summary>
        [EnumMember(Value = "google")]
        Google = 1,

        /// <summary>
        /// Enum Twitter for value: twitter
        /// </summary>
        [EnumMember(Value = "twitter")]
        Twitter = 2,

        /// <summary>
        /// Enum Facebook for value: facebook
        /// </summary>
        [EnumMember(Value = "facebook")]
        Facebook = 3

    }

}
