/*
 * Openfort API
 *
 * Complete Openfort API references and guides can be found at: https://openfort.xyz/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.Reflection;

namespace Openfort.OpenfortSDK.Model
{
    /// <summary>
    /// Specific transaction details based on its type
    /// </summary>
    [JsonConverter(typeof(TransactionIntentDetailsJsonConverter))]
    [DataContract(Name = "TransactionIntent_details")]
    public partial class TransactionIntentDetails : AbstractOpenAPISchema, IEquatable<TransactionIntentDetails>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TransactionIntentDetails" /> class
        /// with the <see cref="ZKSyncDetails" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of ZKSyncDetails.</param>
        public TransactionIntentDetails(ZKSyncDetails actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType = "anyOf";
            if (actualInstance == null)
            {
                throw new ArgumentException("Invalid instance found. Must not be null.");
            }
            this.ActualInstance = actualInstance;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TransactionIntentDetails" /> class
        /// with the <see cref="AccountAbstractionV6Details" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of AccountAbstractionV6Details.</param>
        public TransactionIntentDetails(AccountAbstractionV6Details actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType = "anyOf";
            if (actualInstance == null)
            {
                throw new ArgumentException("Invalid instance found. Must not be null.");
            }
            this.ActualInstance = actualInstance;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TransactionIntentDetails" /> class
        /// with the <see cref="StandardDetails" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of StandardDetails.</param>
        public TransactionIntentDetails(StandardDetails actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType = "anyOf";
            if (actualInstance == null)
            {
                throw new ArgumentException("Invalid instance found. Must not be null.");
            }
            this.ActualInstance = actualInstance;
        }


        private Object _actualInstance;

        /// <summary>
        /// Gets or Sets ActualInstance
        /// </summary>
        public override Object ActualInstance
        {
            get
            {
                return _actualInstance;
            }
            set
            {
                if (value.GetType() == typeof(AccountAbstractionV6Details))
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(StandardDetails))
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(ZKSyncDetails))
                {
                    this._actualInstance = value;
                }
                else
                {
                    throw new ArgumentException("Invalid instance found. Must be the following types: AccountAbstractionV6Details, StandardDetails, ZKSyncDetails");
                }
            }
        }

        /// <summary>
        /// Get the actual instance of `ZKSyncDetails`. If the actual instance is not `ZKSyncDetails`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of ZKSyncDetails</returns>
        public ZKSyncDetails GetZKSyncDetails()
        {
            return (ZKSyncDetails)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `AccountAbstractionV6Details`. If the actual instance is not `AccountAbstractionV6Details`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of AccountAbstractionV6Details</returns>
        public AccountAbstractionV6Details GetAccountAbstractionV6Details()
        {
            return (AccountAbstractionV6Details)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `StandardDetails`. If the actual instance is not `StandardDetails`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of StandardDetails</returns>
        public StandardDetails GetStandardDetails()
        {
            return (StandardDetails)this.ActualInstance;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TransactionIntentDetails {\n");
            sb.Append("  ActualInstance: ").Append(this.ActualInstance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this.ActualInstance, TransactionIntentDetails.SerializerSettings);
        }

        /// <summary>
        /// Converts the JSON string into an instance of TransactionIntentDetails
        /// </summary>
        /// <param name="jsonString">JSON string</param>
        /// <returns>An instance of TransactionIntentDetails</returns>
        public static TransactionIntentDetails FromJson(string jsonString)
        {
            TransactionIntentDetails newTransactionIntentDetails = null;

            if (string.IsNullOrEmpty(jsonString))
            {
                return newTransactionIntentDetails;
            }

            try
            {
                newTransactionIntentDetails = new TransactionIntentDetails(JsonConvert.DeserializeObject<AccountAbstractionV6Details>(jsonString, TransactionIntentDetails.SerializerSettings));
                // deserialization is considered successful at this point if no exception has been thrown.
                return newTransactionIntentDetails;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into AccountAbstractionV6Details: {1}", jsonString, exception.ToString()));
            }

            try
            {
                newTransactionIntentDetails = new TransactionIntentDetails(JsonConvert.DeserializeObject<StandardDetails>(jsonString, TransactionIntentDetails.SerializerSettings));
                // deserialization is considered successful at this point if no exception has been thrown.
                return newTransactionIntentDetails;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into StandardDetails: {1}", jsonString, exception.ToString()));
            }

            try
            {
                newTransactionIntentDetails = new TransactionIntentDetails(JsonConvert.DeserializeObject<ZKSyncDetails>(jsonString, TransactionIntentDetails.SerializerSettings));
                // deserialization is considered successful at this point if no exception has been thrown.
                return newTransactionIntentDetails;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into ZKSyncDetails: {1}", jsonString, exception.ToString()));
            }

            // no match found, throw an exception
            throw new InvalidDataException("The JSON string `" + jsonString + "` cannot be deserialized into any schema defined.");
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TransactionIntentDetails);
        }

        /// <summary>
        /// Returns true if TransactionIntentDetails instances are equal
        /// </summary>
        /// <param name="input">Instance of TransactionIntentDetails to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TransactionIntentDetails input)
        {
            if (input == null)
                return false;

            return this.ActualInstance.Equals(input.ActualInstance);
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ActualInstance != null)
                    hashCode = hashCode * 59 + this.ActualInstance.GetHashCode();
                return hashCode;
            }
        }

    }

    /// <summary>
    /// Custom JSON converter for TransactionIntentDetails
    /// </summary>
    public class TransactionIntentDetailsJsonConverter : JsonConverter
    {
        /// <summary>
        /// To write the JSON string
        /// </summary>
        /// <param name="writer">JSON writer</param>
        /// <param name="value">Object to be converted into a JSON string</param>
        /// <param name="serializer">JSON Serializer</param>
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            writer.WriteRawValue((string)(typeof(TransactionIntentDetails).GetMethod("ToJson").Invoke(value, null)));
        }

        /// <summary>
        /// To convert a JSON string into an object
        /// </summary>
        /// <param name="reader">JSON reader</param>
        /// <param name="objectType">Object type</param>
        /// <param name="existingValue">Existing value</param>
        /// <param name="serializer">JSON Serializer</param>
        /// <returns>The object converted from the JSON string</returns>
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType != JsonToken.Null)
            {
                return TransactionIntentDetails.FromJson(JObject.Load(reader).ToString(Formatting.None));
            }
            return null;
        }

        /// <summary>
        /// Check if the object can be converted
        /// </summary>
        /// <param name="objectType">Object type</param>
        /// <returns>True if the object can be converted</returns>
        public override bool CanConvert(Type objectType)
        {
            return false;
        }
    }

}
