/*
 * Openfort API
 *
 * Complete Openfort API references and guides can be found at: https://openfort.xyz/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;

namespace Openfort.OpenfortSDK.Model
{
    /// <summary>
    /// TransactionConfirmedEventResponse
    /// </summary>
    [DataContract(Name = "TransactionConfirmedEventResponse")]
    public partial class TransactionConfirmedEventResponse : IEquatable<TransactionConfirmedEventResponse>
    {

        /// <summary>
        /// Gets or Sets Object
        /// </summary>
        [DataMember(Name = "object", IsRequired = true, EmitDefaultValue = true)]
        public EntityTypeEVENT Object { get; set; }

        /// <summary>
        /// Gets or Sets Topic
        /// </summary>
        [DataMember(Name = "topic", IsRequired = true, EmitDefaultValue = true)]
        public APITopicTRANSACTIONSUCCESSFUL Topic { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="TransactionConfirmedEventResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TransactionConfirmedEventResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TransactionConfirmedEventResponse" /> class.
        /// </summary>
        /// <param name="id">id (required).</param>
        /// <param name="_object">_object (required).</param>
        /// <param name="createdAt">createdAt (required).</param>
        /// <param name="topic">topic (required).</param>
        /// <param name="numberOfBlocks">numberOfBlocks (required).</param>
        public TransactionConfirmedEventResponse(string id = default(string), EntityTypeEVENT _object = default(EntityTypeEVENT), int createdAt = default(int), APITopicTRANSACTIONSUCCESSFUL topic = default(APITopicTRANSACTIONSUCCESSFUL), double numberOfBlocks = default(double))
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for TransactionConfirmedEventResponse and cannot be null");
            }
            this.Id = id;
            this.Object = _object;
            this.CreatedAt = createdAt;
            this.Topic = topic;
            this.NumberOfBlocks = numberOfBlocks;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [DataMember(Name = "createdAt", IsRequired = true, EmitDefaultValue = true)]
        public int CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets NumberOfBlocks
        /// </summary>
        [DataMember(Name = "numberOfBlocks", IsRequired = true, EmitDefaultValue = true)]
        public double NumberOfBlocks { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TransactionConfirmedEventResponse {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Object: ").Append(Object).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  Topic: ").Append(Topic).Append("\n");
            sb.Append("  NumberOfBlocks: ").Append(NumberOfBlocks).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TransactionConfirmedEventResponse);
        }

        /// <summary>
        /// Returns true if TransactionConfirmedEventResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of TransactionConfirmedEventResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TransactionConfirmedEventResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) &&
                (
                    this.Object == input.Object ||
                    this.Object.Equals(input.Object)
                ) &&
                (
                    this.CreatedAt == input.CreatedAt ||
                    this.CreatedAt.Equals(input.CreatedAt)
                ) &&
                (
                    this.Topic == input.Topic ||
                    this.Topic.Equals(input.Topic)
                ) &&
                (
                    this.NumberOfBlocks == input.NumberOfBlocks ||
                    this.NumberOfBlocks.Equals(input.NumberOfBlocks)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                {
                    hashCode = (hashCode * 59) + this.Id.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.Object.GetHashCode();
                hashCode = (hashCode * 59) + this.CreatedAt.GetHashCode();
                hashCode = (hashCode * 59) + this.Topic.GetHashCode();
                hashCode = (hashCode * 59) + this.NumberOfBlocks.GetHashCode();
                return hashCode;
            }
        }

    }

}
