/*
 * Openfort API
 *
 * Complete Openfort API references and guides can be found at: https://openfort.xyz/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;

namespace Openfort.OpenfortSDK.Model
{
    /// <summary>
    /// Defines TransactionAbstractionType
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum TransactionAbstractionType
    {
        /// <summary>
        /// Enum AccountAbstractionV6 for value: accountAbstractionV6
        /// </summary>
        [EnumMember(Value = "accountAbstractionV6")]
        AccountAbstractionV6 = 1,

        /// <summary>
        /// Enum ZkSync for value: zkSync
        /// </summary>
        [EnumMember(Value = "zkSync")]
        ZkSync = 2,

        /// <summary>
        /// Enum Standard for value: standard
        /// </summary>
        [EnumMember(Value = "standard")]
        Standard = 3

    }

}
